version: 0.8

index_id: messages

doc_mapping:
  field_mappings:
    - name: msg
      type: text
      tokenizer: default
      record: position
      indexed: true
      fast: true
      stored: true

search_settings:
  default_search_fields: [msg]

indexing_settings:
  commit_timeout_secs: 60
